In [1]:
import pyodbc

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# Moudles related to feature selection
from sklearn.feature_selection import RFE, SelectKBest , f_regression

In [2]:
df = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Desktop\Internship\Project 5 (Oil and Gas Industry )\Streamlit Files\Data\Natural_Resources_Revenue.csv")

In [5]:
df.isnull().sum()

Calendar Year             0
Land Class                0
Land Category             0
State                  1955
County                 1955
FIPS Code              1955
Offshore Region       47480
Revenue Type              0
Mineral Lease Type       87
Commodity                 0
Product               22159
Revenue                   0
dtype: int64

In [4]:
df.head()

,Calendar Year,Land Class,Land Category,State,County,FIPS Code,Offshore Region,Revenue Type,Mineral Lease Type,Commodity,Product,Revenue
0,2003,Federal,Onshore,Pennsylvania,Armstrong,42005.0,NaN,Royalties,Oil & Gas,Gas,Unprocessed (Wet) Gas,341.47
1,2003,Federal,Onshore,Louisiana,Natchitoches,22069.0,NaN,Other revenues,Oil & Gas,Oil & gas (pre-production),NaN,331.30
2,2003,Federal,Onshore,Missouri,Iron,29093.0,NaN,Royalties,Hardrock,Copper,Copper Concentrate,57929.02
3,2003,Federal,Onshore,Missouri,Iron,29093.0,NaN,Rents,Hardrock,Hardrock,NaN,-51533.57
4,2003,Federal,Onshore,Missouri,Iron,29093.0,NaN,Royalties,Hardrock,Hardrock,Copper Concentrate,14834.41

In [5]:
df = df[df['Product'].notna()]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26254 entries, 0 to 48412
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Calendar Year       26254 non-null  int64
 1   Land Class          26254 non-null  object
 2   Land Category       26254 non-null  object
 3   State               24889 non-null  object
 4   County              24889 non-null  object
 5   FIPS Code           24889 non-null  float64
 6   Offshore Region     714 non-null    object
 7   Revenue Type        26254 non-null  object
 8   Mineral Lease Type  26254 non-null  object
 9   Commodity           26254 non-null  object
 10  Product             26254 non-null  object
 11  Revenue             26254 non-null  float64
dtypes: float64(2), int64(1), object(9)
memory usage: 2.6+ MB

In [7]:
df.shape

(26254, 12)

In [8]:
df.isnull().sum()

Calendar Year             0
Land Class                0
Land Category             0
State                  1365
County                 1365
FIPS Code              1365
Offshore Region       25540
Revenue Type              0
Mineral Lease Type        0
Commodity                 0
Product                   0
Revenue                   0
dtype: int64

In [9]:
df = df.drop(columns=['Offshore Region','Calendar Year','FIPS Code'])

In [10]:
df.head()

,Land Class,Land Category,State,County,Revenue Type,Mineral Lease Type,Commodity,Product,Revenue
0,Federal,Onshore,Pennsylvania,Armstrong,Royalties,Oil & Gas,Gas,Unprocessed (Wet) Gas,341.47
2,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Copper,Copper Concentrate,57929.02
4,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Copper Concentrate,14834.41
5,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Lead Concentrate,316633.80
6,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Zinc Concentrate,122770.19

In [11]:
df.head()

,Land Class,Land Category,State,County,Revenue Type,Mineral Lease Type,Commodity,Product,Revenue
0,Federal,Onshore,Pennsylvania,Armstrong,Royalties,Oil & Gas,Gas,Unprocessed (Wet) Gas,341.47
2,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Copper,Copper Concentrate,57929.02
4,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Copper Concentrate,14834.41
5,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Lead Concentrate,316633.80
6,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Zinc Concentrate,122770.19

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26254 entries, 0 to 48412
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Land Class          26254 non-null  object
 1   Land Category       26254 non-null  object
 2   State               24889 non-null  object
 3   County              24889 non-null  object
 4   Revenue Type        26254 non-null  object
 5   Mineral Lease Type  26254 non-null  object
 6   Commodity           26254 non-null  object
 7   Product             26254 non-null  object
 8   Revenue             26254 non-null  float64
dtypes: float64(1), object(8)
memory usage: 2.0+ MB

In [14]:
df = df.apply(lambda col: col.fillna(col.mode()[0]) if col.dtype == 'object' else col.fillna(col.median()))

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26254 entries, 0 to 48412
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Land Class          26254 non-null  object
 1   Land Category       26254 non-null  object
 2   State               26254 non-null  object
 3   County              26254 non-null  object
 4   Revenue Type        26254 non-null  object
 5   Mineral Lease Type  26254 non-null  object
 6   Commodity           26254 non-null  object
 7   Product             26254 non-null  object
 8   Revenue             26254 non-null  float64
dtypes: float64(1), object(8)
memory usage: 2.0+ MB

In [16]:
X=df[df.columns.difference(['Revenue'])]
y=df.Revenue

In [17]:
X_train, X_val, y_train, y_val=train_test_split(X, y, test_size=0.3, random_state=37)

In [18]:
df.head()

,Land Class,Land Category,State,County,Revenue Type,Mineral Lease Type,Commodity,Product,Revenue
0,Federal,Onshore,Pennsylvania,Armstrong,Royalties,Oil & Gas,Gas,Unprocessed (Wet) Gas,341.47
2,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Copper,Copper Concentrate,57929.02
4,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Copper Concentrate,14834.41
5,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Lead Concentrate,316633.80
6,Federal,Onshore,Missouri,Iron,Royalties,Hardrock,Hardrock,Zinc Concentrate,122770.19

In [35]:
from catboost import CatBoostRegressor

# Define categorical feature columns
cat_features = ['Land Class', 'Land Category', 'State', 'Revenue Type', 'Mineral Lease Type', 'Commodity','County','Product']

# Initialize CatBoostRegressor
model = CatBoostRegressor(iterations=100, loss_function='RMSE', random_state=42, verbose=0)

# Fit the model
model.fit(X_train, y_train, cat_features=cat_features)

# Predict
y_pred = model.predict(X_val)

# Evaluate
print("MAE:", mean_absolute_error(y_val, y_pred))
print("MAPE:", mean_absolute_percentage_error(y_val, y_pred))
print("RMSE:", mean_squared_error(y_val, y_pred, squared=False))
print("R2 Score:", r2_score(y_val, y_pred))

MAE: 11050810.296352025
MAPE: 6.102988397908715e+20
RMSE: 113029069.56178126
R2 Score: 0.33828659842698494

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [378]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26254 entries, 0 to 48412
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Land Class          26254 non-null  object
 1   Land Category       26254 non-null  object
 2   State               26254 non-null  object
 3   County              26254 non-null  object
 4   Revenue Type        26254 non-null  object
 5   Mineral Lease Type  26254 non-null  object
 6   Commodity           26254 non-null  object
 7   Product             26254 non-null  object
 8   Revenue             26254 non-null  float64
dtypes: float64(1), object(8)
memory usage: 2.0+ MB

In [37]:
from catboost import CatBoostRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error, r2_score

# Define categorical feature columns
cat_features = ['Land Class', 'Land Category', 'State', 'Revenue Type', 'Mineral Lease Type', 'Commodity', 'County', 'Product']

# Initialize the base model
model = CatBoostRegressor(loss_function='RMSE', random_state=42, verbose=0)

# Define hyperparameter space
param_dist = {
    'iterations': [100, 200, 300, 500],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'depth': [4, 6, 8, 10],
    'l2_leaf_reg': [1, 3, 5, 7, 9],
    'bagging_temperature': [0, 1, 2, 5],
    'border_count': [32, 64, 128]
}

# Set up RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=20,   # number of different combinations to try
    cv=3,        # 3-fold cross-validation
    verbose=1,
    random_state=42,
    n_jobs=-1    # use all available cores
)

# Fit RandomizedSearchCV
random_search.fit(X_train, y_train, cat_features=cat_features)

# Best model
best_model = random_search.best_estimator_

# Predict
y_pred = best_model.predict(X_val)

# Evaluate
print("MAE:", mean_absolute_error(y_val, y_pred))
print("MAPE:", mean_absolute_percentage_error(y_val, y_pred))
print("RMSE:", mean_squared_error(y_val, y_pred, squared=False))
print("R2 Score:", r2_score(y_val, y_pred))

# Optional: print best parameters
print("Best Parameters:", random_search.best_params_)

Fitting 3 folds for each of 20 candidates, totalling 60 fits
MAE: 10917112.665283784
MAPE: 3.4523399767810684e+20
RMSE: 105507571.60572314
R2 Score: 0.4234235765129377
Best Parameters: {'learning_rate': 0.1, 'l2_leaf_reg': 5, 'iterations': 300, 'depth': 6, 'border_count': 32, 'bagging_temperature': 0}

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [ ]:
import pickle

# Example: Save a model or DataFrame
with open('Model.pkl', 'wb') as file:
    pickle.dump(your_object, file)